name: EVE Trade
version: v6.2
version_full: Version 6.2
baseurl:
url: https://evetrade.space

destination: dist

exclude:
    - README.md
    - netlify.toml
    - CNAME
    - LICENSE

plugins:
    - jekyll-minifier

jekyll-minifier:
  exclude:
    - release.html
    - sitemap.xml
